# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmailadmin', '0001_initial'),
    ]

    operations = [
        # Set Alias.name.unique = False
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=100),
        ),
        # Add unique_together (Alias.domain, Alias.name)
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('domain', 'name')]),
        ),
    ]
