# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgmailadmin', '0002_alias_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alias',
            name='last_hit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
